version: "3.7"
services:
  db1:
    image: mysql:5.7
    restart: always
    container_name: mysql-db1
    ports:
      - "13331:3306"
    environment:
      - MYSQL_DATABASE=db1
      - MYSQL_ROOT_PASSWORD=db1password
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/mysql/data1:/var/lib/mysql
      - ./db-init1:/docker-entrypoint-initdb.d
    platform: linux/x86_64